server:
  port: 8079  # Port on which the server will listen for requests

spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8080/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com:
      fakepay:
        eurekaserver: ERROR  # Set log level for the application package
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
