server:
    port: 8000  # Port on which the server will listen for requests
    forward-headers-strategy: framework  # Strategy for handling forwarded headers

spring:
    application:
        name: "apigateway"  # Name of the Spring application
    profiles:
        active: "dev"  # Active profile for the application (development profile)
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true #show gateway routes for applications when true
                    lowerCaseServiceId: true
    config:
        import: optional:configserver:http://localhost:8080  # Import configuration from a config server

management:
    endpoints:
        web:
            exposure:
                include: "*"  # Expose all management endpoints over the web
    endpoint:
        gateway:
            enabled: true #show gateway endpoint on actuator
        health:
            probes:
                enabled: true  # Enable health probes for detailed checks
    info:
        env:
            enabled: true  # Enable environment information in the info endpoint
    health:
        readiness-state:
            enabled: true  # Enable readiness checks
        liveness-state:
            enabled: true  # Enable liveness checks


eureka:
    instance:
        preferIpAddress: true  # Prefer IP address for registration
    client:
        fetchRegistry: true  # Fetch registration from the Eureka server
        registerWithEureka: true  # Register the service with Eureka
        serviceUrl:
            defaultZone: http://localhost:8079/eureka/  # Eureka server URL

info:
    app:
        name: "apigateway"  # Application name for the info endpoint
        description: "ApiGateway Application"  # Description of the application

logging:
    level:
        com:
            fakepay:
                apigateway: DEBUG

resilience4j.circuitbreaker:
    configs:
        default:
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 2
            failureRateThreshold: 50
            waitDurationInOpenState: 10000