server:
  port: 8080
  forward-headers-strategy: framework
spring:
  application:
    name: "wallet"
  profiles:
    active: "dev"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: "wallet"
    description: "demo"
    version: "1.0.0"

logging:
  level:
    com:
      demo:
        wallet: ERROR
    org:
      springframework: ERROR
    io:
      springdoc: ERROR

  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"


