server:
  port: 8082  # Port on which the server will listen for requests
  forward-headers-strategy: framework  # Strategy for handling forwarded headers

spring:
  application:
    name: "wallet"  # Name of the Spring application
  profiles:
    active: "dev"  # Active profile for the application (dev)

  datasource:
    url: jdbc:h2:mem:testdb  # JDBC URL for the H2 in-memory database
    driverClassName: org.h2.Driver  # Driver class name for H2
    username: sa  # Database username
    password: ''  # Password for the database (H2 defaults to empty)

  h2:
    console:
      enabled: true  # Enable the H2 database console for web access

  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the database schema
    show-sql: true  # Show SQL statements in logs

  config:
    import: optional:configserver:http://localhost:8080  # Import config from a config server, if available
  cloud:
    function:
      definition: createWallet
    stream:
      bindings:
        createWallet-in-0:
          destination: create-wallet-request
          group: ${spring.application.name}
        createWallet-out-0:
          destination: create-wallet-response
      kafka:
        binder:
          brokers:
            - localhost:9092
            # Specifies the address of the Kafka broker, in this case, running locally on port 9092.

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all management endpoints over the web
  info:
    env:
      enabled: true  # Enable environment information in the info endpoint
  health:
    readiness-state:
      enabled: true  # Enable readiness checks for the application
    liveness-state:
      enabled: true  # Enable liveness checks to verify application health
    endpoint:
      shutdown:
        enabled: true  # Enable the shutdown endpoint for graceful shutdowns
      health:
        probes:
          enabled: true  # Enable detailed health checks

endpoints:
  shutdown:
    enabled: true  # Enable the shutdown endpoint

logging:
  level:
    com:
      fakepay:
        wallet: INFO  # Set log level for the wallet application package
    org:
      springframework: ERROR  # Set log level for Spring framework
    io:
      springdoc: ERROR  # Set log level for SpringDoc
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"  # Custom log pattern

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10  # Number of calls tracked for the circuit breaker state
      permittedNumberOfCallsInHalfOpenState: 2  # Calls allowed in half-open state
      failureRateThreshold: 50  # Failure rate to open the circuit (in percentage)
      waitDurationInOpenState: 10000  # Duration the circuit stays open before transitioning

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3  # Maximum number of retry attempts
      waitDuration: 500  # Duration to wait before next retry
      enableExponentialBackoff: true  # Enable exponential backoff between retries
      exponentialBackoffMultiplier: 2  # Multiplier for the backoff
      ignoreExceptions:
        - java.lang.NullPointerException  # Exceptions to ignore during retry
      retryExceptions:
        - java.util.concurrent.TimeoutException  # Exceptions that will trigger a retry

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000  # Maximum time to wait for acquiring a permit
      limitRefreshPeriod: 5000  # Duration for which the rate limiter refreshes
      limitForPeriod: 1  # Maximum number of requests in the limit refresh period

eureka:
  instance:
    preferIpAddress: true  # Prefer IP address for Eureka instance registration
  client:
    fetchRegistry: true  # Fetch registration from the Eureka server
    registerWithEureka: true  # Register this service with Eureka
    serviceUrl:
      defaultZone: http://localhost:8079/eureka/  # Eureka server URL

info:
  app:
    name: "wallet"  # Name of the application for info endpoint
    description: "Wallet Application"  # Description of the application
    version: "1.0.0"  # Application version