services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak
    ports:
      - "7080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: "start-dev"
    extends:
      file: common-config.yml
      service: network-deploy-service

networks:
  wallet-app:
    driver: "bridge"

volumes:
  keycloak_data: